project:
  name: Lexington to 9th Corridor
  description: "NYC DOT cameras between Lexington Ave and 9th Ave, 34th\u201366th\
    \ streets"
  study_area:
    south_street: 34
    north_street: 66
    east_avenue: Lexington Avenue
    west_avenue: 9 Avenue
    lat_range:
    - 40.742488030283845
    - 40.7775394009829
    lon_range:
    - -74.00578163559483
    - -73.93721383666693
    camera_count: 111
cameras:
- id: fcc24aa5-4da0-48f2-aa43-e70e4677517c
  name: 6 Ave @ 23 St
  latitude: 40.7429025573452
  longitude: -73.992797766009
  area: Manhattan
  priority: medium
- id: fcfbaa3d-13e5-4687-9688-ae1eab37c723
  name: 7 Ave @ 23St
  latitude: 40.7441114245984
  longitude: -73.9956503622239
  area: Manhattan
  priority: medium
- id: 15f7a00b-5afb-4193-a5e4-dfe7710a5dfe
  name: 3 AVE @ 34 ST
  latitude: 40.7457272953698
  longitude: -73.9781169718397
  area: Manhattan
  priority: medium
- id: 0b4bd3d3-1741-49b3-87cc-d0960fa5f424
  name: Lexington Ave @ 34 St
  latitude: 40.7464005840423
  longitude: -73.9797313879486
  area: Manhattan
  priority: medium
- id: d1c219c0-afdd-4fa4-a72c-cc1b1318b99d
  name: 9 Ave @ 23 St
  latitude: 40.7465085991952
  longitude: -74.001366842392
  area: Manhattan
  priority: medium
- id: 17b6c7dd-2aa7-442a-8832-d39051a47d1b
  name: Park Ave @ 34 St
  latitude: 40.7470836952846
  longitude: -73.9813565896605
  area: Manhattan
  priority: medium
- id: 0dc7c2b4-614d-46a3-9610-3ba09f3f1284
  name: 6 Ave @ 30 St
  latitude: 40.747577
  longitude: -73.98971
  area: Manhattan
  priority: medium
- id: f388803c-7e1b-4d67-ad61-87b25934a8a2
  name: 10 Ave @ 23 St
  latitude: 40.747694
  longitude: -74.004174
  area: Manhattan
  priority: medium
- id: a356e2c6-7d95-4d93-85c1-da3d05485d8c
  name: MADISON @ 34 ST
  latitude: 40.7477755134971
  longitude: -73.9829511142234
  area: Manhattan
  priority: medium
- id: 3a3d7bc0-7f35-46ba-9cca-75fe83aac34d
  name: 5 Ave @ 34 St
  latitude: 40.7484435553342
  longitude: -73.9845677012874
  area: Manhattan
  priority: medium
- id: 20b2298a-90cf-463f-b172-0b398a34f061
  name: Park Ave @ 37 St
  latitude: 40.74906
  longitude: -73.979818
  area: Manhattan
  priority: medium
- id: aacb43bf-ed37-44c6-a2fe-8449a7851306
  name: 5 Ave @ 35 St
  latitude: 40.749475
  longitude: -73.98427
  area: Manhattan
  priority: medium
- id: 1e60ade7-c760-48cf-acd9-d9d6cbfa9420
  name: 7 Ave @ 32 St
  latitude: 40.749508
  longitude: -73.991493
  area: Manhattan
  priority: medium
- id: f06979b2-3497-4330-9882-a06c8a442b7c
  name: 6 Ave @ 34 St
  latitude: 40.7498083287543
  longitude: -73.9877461877174
  area: Manhattan
  priority: medium
- id: 2191c11c-1757-4938-a608-a2c6ae0e6486
  name: 9 Ave @ 30 St
  latitude: 40.7501505126346
  longitude: -73.9978981018066
  area: Manhattan
  priority: medium
- id: 5352e130-4668-4be5-a7b9-9e1ce4ea6d4c
  name: 3 Ave @ 42 St
  latitude: 40.7507631595424
  longitude: -73.9744615986273
  area: Manhattan
  priority: medium
- id: ee1b1d85-e8ce-485f-a539-12962933eb9f
  name: 7 Ave @ 34 St
  latitude: 40.7510195668227
  longitude: -73.9906285955498
  area: Manhattan
  priority: medium
- id: 1546f761-039c-4b5c-af5e-75c83c9f603f
  name: Lexington Ave @ 42 St
  latitude: 40.7514494972593
  longitude: -73.976060779701
  area: Manhattan
  priority: medium
- id: b0cbb042-de0a-449f-b5d1-49f68a9bf2ae
  name: 7 Ave @ 36 St
  latitude: 40.752128
  longitude: -73.989657
  area: Manhattan
  priority: medium
- id: f2964d50-042c-4021-8b52-992c08c6ff6f
  name: 8 Ave @ 34 St
  latitude: 40.7521973661027
  longitude: -73.9934562042021
  area: Manhattan
  priority: medium
- id: 83655dbc-7902-4fdb-926c-15fee4396b83
  name: Broadway @ 38 St
  latitude: 40.752453
  longitude: -73.987123
  area: Manhattan
  priority: medium
- id: d1363c77-e061-4414-be82-e6d749254859
  name: Madison Ave @ 42 St
  latitude: 40.7528121596316
  longitude: -73.9792838595713
  area: Manhattan
  priority: medium
- id: 34674be5-4791-47f1-b0b2-2db0ff619732
  name: 6 Ave @ 39 St
  latitude: 40.753352
  longitude: -73.985467
  area: Manhattan
  priority: medium
- id: defa5e30-d6c7-4582-9ceb-03ff0fe7b93a
  name: 9 Ave @ 34 St
  latitude: 40.7534082474864
  longitude: -73.9963142012874
  area: Manhattan
  priority: medium
- id: c6d013c9-e69b-4824-8dad-b6580491d916
  name: Madison Ave @ E 43 St
  latitude: 40.753417
  longitude: -73.97874
  area: Manhattan
  priority: medium
- id: f4e822f7-d2a2-4146-851c-04b2fa6d5265
  name: 5 Ave @ 42 St
  latitude: 40.7534920464028
  longitude: -73.9808970054167
  area: Manhattan
  priority: medium
- id: f96c7b05-c0a1-4d3c-93ae-b025bdea422a
  name: Dyer Ave @ W 34 St
  latitude: 40.754
  longitude: -73.9976
  area: Manhattan
  priority: medium
- id: 879ab924-18ac-4779-a681-395d73a0f0cc
  name: Madison Ave @ E 44 St
  latitude: 40.754038
  longitude: -73.97827
  area: Manhattan
  priority: medium
- id: 5d055599-875a-4010-991f-e7e454889052
  name: 7 Ave @ 40 St
  latitude: 40.754222
  longitude: -73.988355
  area: Manhattan
  priority: medium
- id: e8a479f8-5170-4f1f-b258-b9745c966c71
  name: Vanderbilt Ave @ E 45 St
  latitude: 40.754297
  longitude: -73.976936
  area: Manhattan
  priority: medium
- id: 2bc8aef2-fc97-47e0-84cd-1efc8ee21bfe
  name: 10 Ave @ W 34 St
  latitude: 40.754591
  longitude: -73.999142
  area: Manhattan
  priority: medium
- id: c34ca47e-e375-4b9f-a8d7-f9737566b783
  name: 6 Ave @ 42 St
  latitude: 40.7548488195947
  longitude: -73.9841249380499
  area: Manhattan
  priority: medium
- id: 5bb6d7d8-39ce-43b8-b539-376fbcf73927
  name: 3 Ave @ 49 St
  latitude: 40.7552116061846
  longitude: -73.9712421172846
  area: Manhattan
  priority: medium
- id: 326b2bab-d277-4c5a-9778-a7af791ad151
  name: 9 Ave @ 37 St
  latitude: 40.7552720843545
  longitude: -73.9948547204017
  area: Manhattan
  priority: medium
- id: 434094f8-1be4-4c19-8067-1e11049e46b4
  name: Madison Ave @ 46 St - Manhattan
  latitude: 40.755508
  longitude: -73.977437
  area: Manhattan
  priority: medium
- id: 2589c0d6-c389-4861-b812-4ae68f560eba
  name: 46 St Bet. 5 Ave & Madison Ave
  latitude: 40.7557483
  longitude: -73.9784187
  area: Manhattan
  priority: medium
- id: 9565e94d-66f2-4965-9c13-82d5500d6cfd
  name: Broadway @ 42 St
  latitude: 40.7558094297322
  longitude: -73.9864124090652
  area: Manhattan
  priority: medium
- id: d1d8cd99-7609-409a-a739-f5913dabf4e6
  name: Lexington Ave @ 49 St
  latitude: 40.7558782935853
  longitude: -73.972833819289
  area: Manhattan
  priority: medium
- id: 8933100a-8229-42fe-b4b2-265db410d7ae
  name: 5 Ave @ 46 St
  latitude: 40.756036
  longitude: -73.979014
  area: Manhattan
  priority: medium
- id: bca4a4b0-d73f-4937-9301-85ff8293bd94
  name: 7 AVE @ 42 St
  latitude: 40.75609
  longitude: -73.9869
  area: Manhattan
  priority: medium
- id: 9561ad5f-0eda-460b-ab12-41caa4e0a91e
  name: 47 St Bet. 5 Ave @ Madison Ave- Manhattan
  latitude: 40.75632
  longitude: -73.9777487
  area: Manhattan
  priority: medium
- id: 9e694610-60f1-4939-a1f9-1679e6408f27
  name: 9 Ave @ W 39 St
  latitude: 40.7565
  longitude: -73.994
  area: Manhattan
  priority: medium
- id: d8122408-7092-41ba-a9db-ef8847edeaef
  name: Broadway @ 43 St
  latitude: 40.756583
  longitude: -73.986156
  area: Manhattan
  priority: medium
- id: 45cb119b-0e4a-442e-9410-b810ab8c255d
  name: 7 Ave @ 43 St
  latitude: 40.756691
  longitude: -73.986476
  area: Manhattan
  priority: medium
- id: 03a8a2da-3ac2-45aa-a5ba-4ff7d1ecbd22
  name: 5 Ave @ 47 St
  latitude: 40.756725
  longitude: -73.97883
  area: Manhattan
  priority: medium
- id: 1eb66413-6761-4eb0-bc04-e2533bb74b42
  name: Madison Ave @ 49 St
  latitude: 40.7572361824409
  longitude: -73.9760573417802
  area: Manhattan
  priority: medium
- id: 83bf2591-579d-415b-a0d4-fe39868b46d1
  name: 8 Ave @ 42 St
  latitude: 40.7572405048358
  longitude: -73.9897804546602
  area: Manhattan
  priority: medium
- id: b1d5d592-9e36-478e-bedc-5fb02d836bc3
  name: Sutton Pl @ 58 St
  latitude: 40.7572700598272
  longitude: -73.9599609375
  area: Manhattan
  priority: medium
- id: 19789499-03ac-45de-9401-a7a71ea60d1e
  name: 7 AVE @ 44 St
  latitude: 40.75736
  longitude: -73.986
  area: Manhattan
  priority: medium
- id: bb362cd8-057b-4538-bdee-cf846a725ea0
  name: Dyer Ave @ W 40 St
  latitude: 40.7577
  longitude: -73.9948
  area: Manhattan
  priority: medium
- id: 62ecb539-5e6c-40ff-a771-ea77153cc4ed
  name: Rockefeller Plz @ 48 St (between 5 Ave and 6 Ave)
  latitude: 40.757839
  longitude: -73.979362
  area: Manhattan
  priority: medium
- id: 7a7016c5-a086-40fd-9298-90f17f8b6cea
  name: 5 Ave @ 49 St
  latitude: 40.7579183170509
  longitude: -73.9776717716469
  area: Manhattan
  priority: medium
- id: 053e8995-f8cb-4d02-a659-70ac7c7da5db
  name: Broadway @ 45 St
  latitude: 40.757953
  longitude: -73.98549
  area: Manhattan
  priority: medium
- id: c0f05969-abc6-4fa6-b317-3e6ba03e989a
  name: Dyer Ave @ W 41 St
  latitude: 40.7584
  longitude: -73.9944
  area: Manhattan
  priority: medium
- id: ccd1abb9-0683-4d93-a62f-b2b121612d28
  name: 9 Ave @ 42 St
  latitude: 40.7584430039686
  longitude: -73.9926394975013
  area: Manhattan
  priority: medium
- id: 5c505897-b475-4359-897d-b064bdb9feef
  name: 8 AVE @ 44 St
  latitude: 40.75851
  longitude: -73.9888
  area: Manhattan
  priority: medium
- id: e777e4b4-25cb-4c39-98fc-8d6b25cf7de7
  name: Lexington Ave @ 53 St
  latitude: 40.758559
  longitude: -73.971296
  area: Manhattan
  priority: medium
- id: 482e6d35-2a67-4bbf-b36f-fdf7e031d607
  name: 5 AVE @ 50 St
  latitude: 40.75856
  longitude: -73.9772
  area: Manhattan
  priority: medium
- id: 1927b469-e2dc-4943-a70c-e6e52fd4c48c
  name: Broadway @ 46 St- Quad South
  latitude: 40.758692
  longitude: -73.985371
  area: Manhattan
  priority: medium
- id: dbbf45f6-7d87-46fa-825f-454a7e2bbcad
  name: Broadway @ 46 St- Quad East
  latitude: 40.7587
  longitude: -73.985348
  area: Manhattan
  priority: medium
- id: 76faba94-f9e5-42d7-981e-0cbbbfd4bc21
  name: Broadway @ 46 Street
  latitude: 40.758711
  longitude: -73.985366
  area: Manhattan
  priority: medium
- id: 8cd15417-5b79-4065-9165-4b6ff0ff3f53
  name: Broadway @ 46 St- Quad West
  latitude: 40.75872
  longitude: -73.98539
  area: Manhattan
  priority: medium
- id: f3d82b25-6b10-44c7-ae89-30df075a7ac8
  name: Broadway @ 46 St- Quad North
  latitude: 40.758722
  longitude: -73.98536
  area: Manhattan
  priority: medium
- id: 0c9a2836-c408-48d3-85c7-1977c33d9133
  name: Broadway @ 46 St
  latitude: 40.758744
  longitude: -73.9855
  area: Manhattan
  priority: medium
- id: 82b5a027-8b2d-43ce-ba8e-329382bd61bf
  name: Galvin Ave @ W 40 St
  latitude: 40.7588
  longitude: -73.9976
  area: Manhattan
  priority: medium
- id: b331d9d1-c081-4476-8302-83445ac196e7
  name: Dyer Ave @ 42 Street
  latitude: 40.7589811180163
  longitude: -73.9939438000961
  area: Manhattan
  priority: medium
- id: 9e3e26ae-d49f-4f64-ba99-113b779c25a2
  name: Park Ave @ 53 St
  latitude: 40.759067
  longitude: -73.97261
  area: Manhattan
  priority: medium
- id: 1dddf912-4718-4b2a-94dd-1f793a9ed22c
  name: 6 Ave @ 49 St
  latitude: 40.759281077223
  longitude: -73.9808977882913
  area: Manhattan
  priority: medium
- id: 9f6b60c8-b940-4eec-a3c5-4b60d24c751b
  name: YORK AVENUE @ EAST 60 STREET
  latitude: 40.759324
  longitude: -73.95905
  area: Manhattan
  priority: medium
- id: b55781b8-827c-40e3-b094-27c289d22f7a
  name: 10 Ave @ 42 St
  latitude: 40.759663
  longitude: -73.995317
  area: Manhattan
  priority: medium
- id: 4f3f56e3-f68e-4b60-a4ba-153ecb9094f7
  name: 6 AVE @ 50 St
  latitude: 40.75994
  longitude: -73.9805
  area: Manhattan
  priority: medium
- id: 62b3062d-542f-40f1-86ec-206710e789b6
  name: 3 Ave @ 57 St
  latitude: 40.760252895987
  longitude: -73.967542473241
  area: Manhattan
  priority: medium
- id: fc7db899-7a79-41f3-b9b1-b23ce64c5a5e
  name: 7 Ave @ 49 St
  latitude: 40.7604823513464
  longitude: -73.983738054794
  area: Manhattan
  priority: medium
- id: 180dcc87-d861-43e3-8898-9ad5ee1a26a9
  name: Lexington Ave @ 57 ST
  latitude: 40.7609271914359
  longitude: -73.9691468531185
  area: Manhattan
  priority: medium
- id: 74bdd301-683c-4ea7-abf2-a5715dca8e17
  name: York Ave @ 63 St
  latitude: 40.761216
  longitude: -73.957815
  area: Manhattan
  priority: medium
- id: f4d2c0f5-0148-45e7-95ba-a5185d8e8060
  name: Park Ave @ 57 St
  latitude: 40.761615778381
  longitude: -73.9707524905279
  area: Manhattan
  priority: medium
- id: 4850e464-1111-4b5d-a72d-f54a0e12a789
  name: 8 Ave @ 49 St
  latitude: 40.761676
  longitude: -73.986581
  area: Manhattan
  priority: medium
- id: 0a49d947-2a5b-498d-a386-2cef5ce883fa
  name: "50 St Btwn\_8 Ave & Broadway"
  latitude: 40.761861
  longitude: -73.985123
  area: Manhattan
  priority: medium
- id: 3d8e276f-b179-414d-a506-679d5e559d3e
  name: Broadway @ 51 St
  latitude: 40.762077539856
  longitude: -73.9836422756604
  area: Manhattan
  priority: medium
- id: 421960d6-54a8-4f12-a5ee-7a07390def4c
  name: MADISON @ 57 ST
  latitude: 40.7622962700164
  longitude: -73.9723570534941
  area: Manhattan
  priority: medium
- id: 404fac12-9b5c-430b-a01b-12b50d39521c
  name: 9 Ave @ 49 St
  latitude: 40.7628734544829
  longitude: -73.9894306186342
  area: Manhattan
  priority: medium
- id: 9c4c2657-6796-4953-bbe6-c50f24bb5820
  name: 5 Ave @ 57 St
  latitude: 40.7629820055328
  longitude: -73.9739858644822
  area: Manhattan
  priority: medium
- id: 2be7f4d2-3a72-45ba-95ad-b526643ef248
  name: West Street @ Intrepid
  latitude: 40.763103
  longitude: -73.999643
  area: Manhattan
  priority: medium
- id: 4ebe49c8-3e68-43f7-b415-da3db9f72693
  name: 7 Ave @ 54 St
  latitude: 40.763617
  longitude: -73.981436
  area: Manhattan
  priority: medium
- id: b5a78bda-3ca9-4ad4-bd03-4cee70baba2d
  name: 5 Ave @ 59 St
  latitude: 40.764289
  longitude: -73.973023
  area: Manhattan
  priority: medium
- id: e229e0fd-559b-4c1e-bcba-ac23db1d01e3
  name: 6 Ave @ 57 St
  latitude: 40.7643348872061
  longitude: -73.9772018595711
  area: Manhattan
  priority: medium
- id: a4c12003-9638-473d-bfe3-dddf509c80b8
  name: 6 Ave @ 58 St
  latitude: 40.765024
  longitude: -73.976689
  area: Manhattan
  priority: medium
- id: cd949f21-54b2-4d11-8aae-4ffba8654271
  name: 5 Ave @ E 60 St
  latitude: 40.765165
  longitude: -73.972692
  area: Manhattan
  priority: medium
- id: f0b924fe-0df6-4ac2-85a2-5d2b96d081d5
  name: 7 Ave @ 57 St
  latitude: 40.765534775125
  longitude: -73.9800400250842
  area: Manhattan
  priority: medium
- id: 332f161d-47cb-4c8a-b6b6-5ad48a55c978
  name: Ave of Americas @ Central Park South
  latitude: 40.765767
  longitude: -73.976123
  area: Manhattan
  priority: medium
- id: d78ebdc6-2211-479e-bda6-59d79db20258
  name: 8 Ave @ 57 St
  latitude: 40.766796
  longitude: -73.9829
  area: Manhattan
  priority: medium
- id: d45fb588-de4c-4139-9e27-5b2d4c371b3d
  name: York Ave @ 72 St
  latitude: 40.76687
  longitude: -73.9538
  area: Manhattan
  priority: medium
- id: 85809312-60f2-4a52-a694-82628529c05a
  name: Central Park S @ Columbus Cr
  latitude: 40.7677366852749
  longitude: -73.9814615249633
  area: Manhattan
  priority: medium
- id: 78a5c61d-9dce-4b52-b0da-bf7d22c1f501
  name: 8 Ave @ Columbus Cr South
  latitude: 40.767775
  longitude: -73.982089
  area: Manhattan
  priority: medium
- id: 37e2a4b6-2fbd-42f5-9d2d-130b664783f2
  name: 9 Ave @ 57 St
  latitude: 40.7679306900999
  longitude: -73.9857235137761
  area: Manhattan
  priority: medium
- id: c880d0c4-db84-44c2-9f00-62f21a83b5d0
  name: Broadway @ Columbus Circle
  latitude: 40.76861
  longitude: -73.981747
  area: Manhattan
  priority: medium
- id: 81db80c2-13fe-4ae7-8b47-c08aa42d512f
  name: 5 Ave @ 66 St
  latitude: 40.768651
  longitude: -73.969814
  area: Manhattan
  priority: medium
- id: d4bbce49-b087-4524-a835-08cb253926a7
  name: 10 Ave @ 57 St
  latitude: 40.769126
  longitude: -73.98858
  area: Manhattan
  priority: medium
- id: 5caa3ace-277b-42db-97bd-585f29b0d49f
  name: Central Park West @ W 61 St
  latitude: 40.769303
  longitude: -73.980882
  area: Manhattan
  priority: medium
- id: 65440c6b-ee6c-4406-8542-2992b6edf3f5
  name: Lexington Ave @ 72 St
  latitude: 40.769719
  longitude: -73.962021
  area: Manhattan
  priority: medium
- id: ec9eda79-e250-4e6f-a8f6-e51021fb054f
  name: Amsterdam Ave @ 60 St
  latitude: 40.770207
  longitude: -73.986869
  area: Manhattan
  priority: medium
- id: 3f04a686-f97c-4187-8968-cb09265e08ff
  name: Central Park @ 72nd St Post 37
  latitude: 40.770785
  longitude: -73.978337
  area: Manhattan
  priority: medium
- id: b062d611-e0e8-40be-a180-c583391276f5
  name: Park Ave @ 72 St
  latitude: 40.77114
  longitude: -73.963907
  area: Manhattan
  priority: medium
- id: 03d9fe0d-7c26-4929-a350-ab0a58a430c6
  name: 5 Ave @ 72 St
  latitude: 40.7715393676332
  longitude: -73.9669132232666
  area: Manhattan
  priority: medium
- id: 4f8c2e84-c15a-4474-91fb-7e14554d4c4e
  name: Central Park West @ 65 St
  latitude: 40.771797
  longitude: -73.979217
  area: Manhattan
  priority: medium
- id: 04e09ed5-2d97-4e29-8438-b87748850dbb
  name: Columbus Ave @ 65 St
  latitude: 40.7721568767076
  longitude: -73.9817190170288
  area: Manhattan
  priority: medium
- id: 3df06012-4c10-46e1-81d0-55405342e8df
  name: 3 AVE @ 76 St
  latitude: 40.77234
  longitude: -73.9587
  area: Manhattan
  priority: medium
- id: 7e2400e3-cad2-407a-927b-d575a35048e3
  name: Central Park West @ 66 St
  latitude: 40.772441
  longitude: -73.978751
  area: Manhattan
  priority: medium
- id: 41397b64-d035-4b41-a03e-170fe4103d89
  name: Park Ave @ 79 St
  latitude: 40.775652
  longitude: -73.96035
  area: Manhattan
  priority: medium
- id: 984ebbad-ca64-41d8-8008-63aaae316952
  name: Central Park West @ 72 St
  latitude: 40.776225
  longitude: -73.975974
  area: Manhattan
  priority: medium
- id: a4bb497d-7e15-47c4-9787-374b013efbbe
  name: Madison Ave @ 79 St
  latitude: 40.776331
  longitude: -73.962123
  area: Manhattan
  priority: medium
